version: '3.8'
services:
  learning-tutor:
    build:
      context: ./frontend/learning-tutor 
      dockerfile: Dockerfile 
    stdin_open: true
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./frontend/learning-tutor:/app"
      - "/app/node_modules"


