version: '3'

tasks:
  clone:
    desc: "Clone all repositories"
    cmds:
      - git clone https://github.com/lpazzim/learning-tutor frontend/learning-tutor
 
  install:
    desc: "Install all dependencies for all applications"
    cmds:
      - task install:learning-tutor

  install:learning-tutor:
    desc: "Instala dependências para learning-tutor"
    cmds:
      - cd frontend/learning-tutor && pnpm install

  build:learning-tutor:
      desc: "Gera build para learning-tutor"
      cmds:
        - cd frontend/learning-tutor && pnpm install && pnpm run build

  docker:
      desc: "Sobe os containers Docker para todos os aplicativos"
      cmds:
        - docker-compose up

