name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - .github/**
      - husky/**
      - .vscode/**
      - .docs/**
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - .github/**
      - husky/**
      - .vscode/**
      - .docs/**
  # workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
     - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.MYBOT_APP_ID }}
          private_key: ${{ secrets.MYBOT_PRIVATE_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Publish release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: pnpm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}
  