name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - .github/**
      - husky/**
      - .vscode/**
      - .docs/**
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - .github/**
      - husky/**
      - .vscode/**
      - .docs/**
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  deploy_and_publish_release:
    needs: build
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Publish release
        if: github.event_name == 'push' && github.event_name == 'workflow_dispatch'
        run: pnpm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}